version: '2.2'
services:
  auth-agents:
    build:
      context: ./
      dockerfile: Dockerfile
    image: thewilly/auth-agents
    ports:
      - 80:8080
    networks:
      - network1
    scale: 1
 
networks:
  network1: